//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property365.Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public int PermissionTypeID { get; set; }
        public int Quantity { get; set; }
    
        public virtual PermissionType PermissionType { get; set; }
        public virtual Role Role { get; set; }
    }
}
