//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMe.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Properties = new HashSet<MyProperty>();
        }
    
        public int ID { get; set; }
        public long UserID { get; set; }
        public int AgencyID { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<MyProperty> Properties { get; set; }
    }
}
