//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMe.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyProperty
    {
        public MyProperty()
        {
            this.PropertyPictures = new HashSet<PropertyPicture>();
        }
    
        public long ID { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public int Area { get; set; }
        public int Bedroom { get; set; }
        public int Bathroom { get; set; }
        public string ReferenceNumber { get; set; }
        public string Description { get; set; }
        public int AgentID { get; set; }
        public System.Data.Entity.Spatial.DbGeography Location { get; set; }
        public bool IsSale { get; set; }
        public bool IsRent { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<PropertyPicture> PropertyPictures { get; set; }
    }
}
