//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMe.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.Categories = new HashSet<Category>();
            this.PropertyPictures = new HashSet<PropertyPicture>();
        }
    
        public long ID { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<PropertyPicture> PropertyPictures { get; set; }
    }
}
