//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMe.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyPicture
    {
        public long ID { get; set; }
        public long PropertyID { get; set; }
        public long PictureID { get; set; }
    
        public virtual Picture Picture { get; set; }
        public virtual MyProperty Property { get; set; }
    }
}
