//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyMe.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Agencies = new HashSet<Agency>();
            this.Agents = new HashSet<Agent>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public Nullable<long> PictureID { get; set; }
        public int RoleID { get; set; }
        public bool isActive { get; set; }
    
        public virtual ICollection<Agency> Agencies { get; set; }
        public virtual ICollection<Agent> Agents { get; set; }
        public virtual Role Role { get; set; }
    }
}
