//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace People365.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<long> UserID { get; set; }
        public long PropertyID { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual MyProperty MyProperty { get; set; }
        public virtual PropertyUser PropertyUser { get; set; }
    }
}
