//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace People365.WCF
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Picture
    {
        public Picture()
        {
            this.PropertyUsers = new HashSet<PropertyUser>();
        }

        public long ID { get; set; }
        public byte[] Image { get; set; }


        [IgnoreDataMember]
        public virtual ICollection<PropertyUser> PropertyUsers { get; set; }
    }
}
