//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace People365.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public long ID { get; set; }
        public long UserID { get; set; }
        public long PropertyID { get; set; }
    
        public virtual MyProperty MyProperty { get; set; }
        public virtual PropertyUser PropertyUser { get; set; }
    }
}
