//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProperty365Service")]
    public interface IProperty365Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty365Service/GetAgentList", ReplyAction="http://tempuri.org/IProperty365Service/GetAgentListResponse")]
        PropertyMe.EF.Agent[] GetAgentList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty365Service/GetAgentList", ReplyAction="http://tempuri.org/IProperty365Service/GetAgentListResponse")]
        System.Threading.Tasks.Task<PropertyMe.EF.Agent[]> GetAgentListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty365Service/AddAgent", ReplyAction="http://tempuri.org/IProperty365Service/AddAgentResponse")]
        bool AddAgent(PropertyMe.EF.Agent newAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty365Service/AddAgent", ReplyAction="http://tempuri.org/IProperty365Service/AddAgentResponse")]
        System.Threading.Tasks.Task<bool> AddAgentAsync(PropertyMe.EF.Agent newAgent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty365Service/GetAgent", ReplyAction="http://tempuri.org/IProperty365Service/GetAgentResponse")]
        PropertyMe.EF.Agent GetAgent(string agentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty365Service/GetAgent", ReplyAction="http://tempuri.org/IProperty365Service/GetAgentResponse")]
        System.Threading.Tasks.Task<PropertyMe.EF.Agent> GetAgentAsync(string agentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty365Service/UpdateAgent", ReplyAction="http://tempuri.org/IProperty365Service/UpdateAgentResponse")]
        bool UpdateAgent(PropertyMe.EF.Agent contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty365Service/UpdateAgent", ReplyAction="http://tempuri.org/IProperty365Service/UpdateAgentResponse")]
        System.Threading.Tasks.Task<bool> UpdateAgentAsync(PropertyMe.EF.Agent contact);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty365Service/DeleteAgent", ReplyAction="http://tempuri.org/IProperty365Service/DeleteAgentResponse")]
        bool DeleteAgent(string agentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProperty365Service/DeleteAgent", ReplyAction="http://tempuri.org/IProperty365Service/DeleteAgentResponse")]
        System.Threading.Tasks.Task<bool> DeleteAgentAsync(string agentID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProperty365ServiceChannel : ConsoleApplication1.ServiceReference1.IProperty365Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Property365ServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IProperty365Service>, ConsoleApplication1.ServiceReference1.IProperty365Service {
        
        public Property365ServiceClient() {
        }
        
        public Property365ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Property365ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Property365ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Property365ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PropertyMe.EF.Agent[] GetAgentList() {
            return base.Channel.GetAgentList();
        }
        
        public System.Threading.Tasks.Task<PropertyMe.EF.Agent[]> GetAgentListAsync() {
            return base.Channel.GetAgentListAsync();
        }
        
        public bool AddAgent(PropertyMe.EF.Agent newAgent) {
            return base.Channel.AddAgent(newAgent);
        }
        
        public System.Threading.Tasks.Task<bool> AddAgentAsync(PropertyMe.EF.Agent newAgent) {
            return base.Channel.AddAgentAsync(newAgent);
        }
        
        public PropertyMe.EF.Agent GetAgent(string agentID) {
            return base.Channel.GetAgent(agentID);
        }
        
        public System.Threading.Tasks.Task<PropertyMe.EF.Agent> GetAgentAsync(string agentID) {
            return base.Channel.GetAgentAsync(agentID);
        }
        
        public bool UpdateAgent(PropertyMe.EF.Agent contact) {
            return base.Channel.UpdateAgent(contact);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAgentAsync(PropertyMe.EF.Agent contact) {
            return base.Channel.UpdateAgentAsync(contact);
        }
        
        public bool DeleteAgent(string agentID) {
            return base.Channel.DeleteAgent(agentID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAgentAsync(string agentID) {
            return base.Channel.DeleteAgentAsync(agentID);
        }
    }
}
