CREATE TABLE [dbo].[Agent]
(
	[ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Email] NVARCHAR(50) NULL, 
    [Phone] NVARCHAR(50) NULL, 
    [Mobile] NVARCHAR(50) NOT NULL, 
    [PictureID] CHAR(36) NULL, 
    [AgencyID] CHAR(36) NOT NULL
)
