CREATE TABLE [dbo].[User]
(
	[ID] BIGINT NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [Password] NVARCHAR(20) NOT NULL, 
	[Tel] NVARCHAR(20) NOT NULL, 
    [Email] NVARCHAR(50) NULL, 
	[Description] NVARCHAR(300) NULL,
	[PictureID] bigint NULL,
    [RoleID] INT NOT NULL,
	[isActive] BIT NOT NULL DEFAULT 0
CONSTRAINT [FK_User_Role] FOREIGN KEY ([RoleID]) REFERENCES [Role]([ID]),
)
